import type { Difficulty } from "./game-types.ts";
export interface Puzzle {
  id: string;
  title: string;
  topic: string;
  prompt: string;
  answer: number;
  hint: string;
  solution: string;
  requires?: string[];
}
const p = (
  id: string,
  title: string,
  topic: string,
  prompt: string,
  answer: number,
  hint: string,
  solution: string,
): Puzzle => ({ id, title, topic, prompt, answer, hint, solution });
// Answers stay on the server. Only public puzzle descriptions are sent to players.
export const PUZZLES: Record<Difficulty, Puzzle[][]> = {
  junior: [
    [
      p(
        "j0a",
        "The keypad",
        "Order of operations",
        "The keypad reads 8 + 6 × 3. Enter its value.",
        26,
        "Multiplication comes before addition.",
        "6 × 3 = 18; 8 + 18 = 26.",
      ),
      p(
        "j0b",
        "The missing page",
        "Number patterns",
        "A torn notebook reads 4, 9, 14, 19, __. What number comes next?",
        24,
        "Look at the difference between neighbours.",
        "Each number increases by 5, so 19 + 5 = 24.",
      ),
      p(
        "j0c",
        "The supply drawer",
        "Arithmetic",
        "Voss has 7 boxes of 8 pencils. He gives away 19 pencils. How many remain?",
        37,
        "Find the total first, then subtract.",
        "7 × 8 = 56; 56 − 19 = 37.",
      ),
    ],
    [
      p(
        "j1a",
        "The antidote",
        "Fractions",
        "A bottle contains 120 mL. You need three quarters of it. How many mL should you pour?",
        90,
        "Divide by 4, then multiply by 3.",
        "120 ÷ 4 × 3 = 90 mL.",
      ),
      p(
        "j1b",
        "The discount label",
        "Percentages",
        "A lab coat costs 80 credits with a 25% discount. What is the final price?",
        60,
        "Find a quarter of 80 and subtract it.",
        "25% of 80 is 20; 80 − 20 = 60 credits.",
      ),
      p(
        "j1c",
        "The mixture",
        "Ratios",
        "Mix green and blue liquid in the ratio 2:3. If the total is 50 mL, how many mL must be green?",
        20,
        "There are 5 equal parts. Green uses 2.",
        "50 ÷ 5 = 10 per part; 2 × 10 = 20 mL.",
      ),
    ],
    [
      p(
        "j2a",
        "The silent alarm",
        "One-step equations",
        "The alarm will stop when x + 17 = 42. Find x.",
        25,
        "Subtract 17 from both sides.",
        "x = 42 − 17 = 25.",
      ),
      p(
        "j2b",
        "The power switch",
        "Powers",
        "The generator asks for 2⁴ + 3². Enter the value.",
        25,
        "2⁴ means 2 × 2 × 2 × 2; 3² means 3 × 3.",
        "2⁴ = 16 and 3² = 9; 16 + 9 = 25.",
      ),
      p(
        "j2c",
        "The hidden variable",
        "Two-step equations",
        "A locked cabinet reads 3x − 5 = 16. Find x.",
        7,
        "Add 5 first, then divide by 3.",
        "3x = 21, so x = 7.",
      ),
    ],
    [
      p(
        "j3a",
        "The floor panel",
        "Area",
        "A rectangular floor panel is 9 cm long and 6 cm wide. What is its area in cm²?",
        54,
        "Rectangle area = length × width.",
        "9 × 6 = 54 cm².",
      ),
      p(
        "j3b",
        "The triangle dial",
        "Angles",
        "A triangle has angles of 48° and 67°. Find the third angle in degrees.",
        65,
        "A triangle's angles add to 180°.",
        "180 − 48 − 67 = 65°.",
      ),
      p(
        "j3c",
        "The fence code",
        "Perimeter",
        "A rectangle has perimeter 34 cm and length 10 cm. Find its width in cm.",
        7,
        "Perimeter = 2 × (length + width).",
        "34 ÷ 2 = 17; width = 17 − 10 = 7 cm.",
      ),
    ],
    [
      p(
        "j4a",
        "The balance lock",
        "Equations",
        "The final door reads 4x + 3 = 2x + 19. Find x.",
        8,
        "Move the x terms to one side and numbers to the other.",
        "2x = 16, so x = 8.",
      ),
      p(
        "j4b",
        "The probability safe",
        "Probability",
        "A bag contains 3 green and 5 blue keys. What is the probability of picking green? Enter a fraction or decimal.",
        3 / 8,
        "Divide the number of green keys by all keys.",
        "3 green keys out of 8 total gives 3/8 = 0.375.",
      ),
      p(
        "j4c",
        "The last grade",
        "Averages",
        "Your three test scores average 80. The first two are 72 and 84. What is the third?",
        84,
        "Three scores must total 3 × 80.",
        "240 − 72 − 84 = 84.",
      ),
    ],
  ],
  senior: [
    [
      p(
        "s0a",
        "The keypad",
        "Order of operations",
        "Enter the value of 18 − 2 × (3 + 4).",
        4,
        "Work inside the brackets, then multiply.",
        "3 + 4 = 7; 18 − 2 × 7 = 4.",
      ),
      p(
        "s0b",
        "The missing page",
        "Number patterns",
        "Find the next term: 3, 7, 15, 31, __.",
        63,
        "Each term is twice the previous term plus 1.",
        "31 × 2 + 1 = 63.",
      ),
      p(
        "s0c",
        "The supply drawer",
        "Signed numbers",
        "The freezer is at −8°C. It warms by 15°C, then cools by 4°C. What is its final temperature?",
        3,
        "Track each temperature change with its sign.",
        "−8 + 15 − 4 = 3°C.",
      ),
    ],
    [
      p(
        "s1a",
        "The antidote",
        "Fractions",
        "Enter the value of 3/4 + 5/8 as a fraction or decimal.",
        11 / 8,
        "Convert 3/4 into eighths.",
        "6/8 + 5/8 = 11/8 = 1.375.",
      ),
      p(
        "s1b",
        "The discount label",
        "Successive percentages",
        "A machine costs 200 credits. Its price rises 10%, then falls 10%. Find the final price.",
        198,
        "The second percentage uses the new price.",
        "200 × 1.10 × 0.90 = 198 credits.",
      ),
      p(
        "s1c",
        "The mixture",
        "Ratios",
        "Green to blue liquid is 3:5. Adding 12 mL of green makes the amounts equal. How many mL of blue were there?",
        30,
        "Write the original amounts as 3k and 5k.",
        "3k + 12 = 5k; k = 6; blue = 5 × 6 = 30 mL.",
      ),
    ],
    [
      p(
        "s2a",
        "The silent alarm",
        "Linear equations",
        "Solve 5(x − 2) = 3x + 8. Enter x.",
        9,
        "Expand the bracket, then collect x terms.",
        "5x − 10 = 3x + 8; 2x = 18; x = 9.",
      ),
      p(
        "s2b",
        "The power switch",
        "Exponents",
        "Enter the value of 2⁵ × 2³ ÷ 2⁶.",
        4,
        "For the same base, add exponents when multiplying and subtract when dividing.",
        "2^(5 + 3 − 6) = 2² = 4.",
      ),
      p(
        "s2c",
        "The hidden variable",
        "Square roots",
        "Find the positive value of x when x² = 144.",
        12,
        "Find a positive number that multiplies by itself to give 144.",
        "12 × 12 = 144, so the positive root is 12.",
      ),
    ],
    [
      p(
        "s3a",
        "The laser bridge",
        "Pythagoras",
        "A right triangle has shorter sides 6 cm and 8 cm. Find the hypotenuse in cm. Formula: c² = a² + b².",
        10,
        "Square 6 and 8, add, then take the square root.",
        "c² = 36 + 64 = 100; c = 10 cm.",
      ),
      p(
        "s3b",
        "The circle dial",
        "Circles",
        "A circular dial has radius 7 cm. Find its area in cm² using π = 22/7. Formula: area = πr².",
        154,
        "Square the radius before multiplying by π.",
        "(22/7) × 7² = 154 cm².",
      ),
      p(
        "s3c",
        "The angled lock",
        "Trigonometry",
        "For a right triangle, sin θ = opposite / hypotenuse. If sin θ = 3/5 and the hypotenuse is 20 cm, find the opposite side.",
        12,
        "Multiply the hypotenuse by 3/5.",
        "Opposite = 20 × 3/5 = 12 cm.",
      ),
    ],
    [
      p(
        "s4a",
        "The balance lock",
        "Simultaneous equations",
        "Two locks satisfy x + y = 13 and x − y = 5. Find x.",
        9,
        "Add the two equations to eliminate y.",
        "2x = 18, so x = 9 (and y = 4).",
      ),
      p(
        "s4b",
        "The probability safe",
        "Probability",
        "A bag holds 3 green and 2 blue keys. Pick two without replacement. What is the probability both are green? Enter a fraction or decimal.",
        3 / 10,
        "Multiply 3/5 by the probability of green after one green key is removed.",
        "(3/5) × (2/4) = 6/20 = 3/10 = 0.3.",
      ),
      p(
        "s4c",
        "The last grade",
        "Quadratics",
        "The final lock reads x² − 7x + 12 = 0. Enter the larger solution.",
        4,
        "Find two numbers whose sum is 7 and product is 12.",
        "(x − 3)(x − 4) = 0. The roots are 3 and 4; the larger is 4.",
      ),
    ],
  ],
};
export const DETENTION: Puzzle[][] = [
  [
    p(
      "d1a",
      "The warning slip",
      "Multiplication",
      "Voss demands a quick answer: 9 × 6 = ?",
      54,
      "9 × 6 is 10 × 6 minus 6.",
      "60 − 6 = 54.",
    ),
  ],
  [
    p(
      "d2a",
      "Detention lock A",
      "Arithmetic",
      "A switch reads 36 ÷ 4 + 7. Enter the value.",
      16,
      "Divide before adding.",
      "36 ÷ 4 = 9; 9 + 7 = 16.",
    ),
    p(
      "d2b",
      "Detention lock B",
      "Percentages",
      "Find 50% of 46.",
      23,
      "50% means one half.",
      "46 ÷ 2 = 23.",
    ),
  ],
  [
    p(
      "d3a",
      "Code fragment A",
      "Division",
      "Find code fragment A: 18 ÷ 3.",
      6,
      "Split 18 into 3 equal groups.",
      "18 ÷ 3 = 6.",
    ),
    p(
      "d3b",
      "Code fragment B",
      "Percentages",
      "Find code fragment B: 35% of 20.",
      7,
      "10% of 20 is 2. Use 30% plus 5%.",
      "0.35 × 20 = 7.",
    ),
    {
      ...p(
        "d3c",
        "The probation exit",
        "Decode the code",
        "Use fragment A as the tens digit and fragment B as the ones digit. Enter the two-digit exit code.",
        67,
        "The code is 10 × A + B.",
        "A = 6 and B = 7. The code is 67.",
      ),
      requires: ["d3a", "d3b"],
    },
  ],
];
